name: Release new versions

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (no v prefix)'
        required: true
        default: '0.0.0'

permissions:
  contents: read
  packages: write

jobs:
  publish-lib:
    name: Publish lib to npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lib

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Publish lib to npm
        run: pnpm publish --access public
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-cli:
    name: Publish CLI to npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/cli

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Publish lib to npm
        run: pnpm publish --access public
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  docker-release:
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get release version from tag
        if: ${{ github.event_name == 'push' }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
      - name: Get release version from input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            corentinth/enclosed:latest
            corentinth/enclosed:${{ env.RELEASE_VERSION }}
            ghcr.io/corentinth/enclosed:latest
            ghcr.io/corentinth/enclosed:${{ env.RELEASE_VERSION}}
